#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 01, 2022 07:05:03 PM +0300  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import clientf.tk_frames.login_page as login_page


def main(func_dict, top, *args):
    '''Main entry point for the application.'''
    global root
    root = top
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = login_page.Toplevel1(func_dict, _top1)
    root.mainloop()

if __name__ == '__main__':
    login_page.start_up()




